name: Build and publish new Docker image
on:
  push:
    branches: main

jobs:
  # Build and push the latest image
  docker-publish:
    name: "Docker build and push image"
    runs-on: ubuntu-latest
    steps:
      - # Login to Docker Hub
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PAT }}

      - # Docker Buildx
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - # Build and push latest image
        name: Docker build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.USERNAME }}/ntnui-membership-bot:latest,${{ secrets.USERNAME }}/ntnui-membership-bot:${{ github.sha }}
